### ISSUE TITLE
Devastating wound

### ISSUE THREAD

**Issue by homurax1988** [toadchild/40kdice#14]
Noticed that the damage for devastating wound and Lethal hits seem to be the same.
Devastating wound should be higher than lethal hits since Devastating wound ignores saves and inv saves, while the lethal hits seems pretty correct.

Devastating would = attack_roll(attacker)*(((hitroll*woundroll_result+autowound)*savevalue)+mortalwound)*damage(attacker)

am quite new to Warhammer and coding so... I might be wrong

**Comment by toadchild** [comment]
Hi, can you paste in the links to the tests you were running? That'll help me understand the specifics of that scenario and we can figure out if the calculator is producing the correct results.

**Comment by homurax1988** [comment]
Hello, here is the link: 
https://40k.ghostlords.com/dice/#attacks=4&bs=3&ap=-1&s=5&d=2&t=4&save=4&wounds=2&wound_dev

so when I toggle between lethal hits and devastating wound, it appears that the damage remains the same, despite devastating wound is mortal wound, which ignores saves and inv saves. so I was wondering if I am missing something here.

Cheers.

**Comment by toadchild** [comment]
On the basic (no special abilities) attack, your chance of doing damage is: `hit (4/6) * wound (4/6) * failed save (4/6) = 30%` Please note that the probability being rolled at each step is the same!

If you have lethal hits, then a hit roll of 6 (1/3 of successful hits) will bypass the wound roll and go directly to the armor save. If you have devastating wounds, a wound roll of 6 (1/3 of successful wounds) will bypass the armor save and cause direct wounds. In each case, 1/3 of the time you are bypassing a 4/6 probability roll. If your wound roll and armor save have different probabilities, you will see a different effect from lethal hits vs. devastating wounds.

For example, if you are wounding on 2s, then [lethal](https://40k.ghostlords.com/dice/#attacks=4&bs=3&ap=-1&s=8&d=2&t=4&save=4&wounds=2&hit_leth) is weaker than [devastating](https://40k.ghostlords.com/dice/#attacks=4&bs=3&ap=-1&s=8&d=2&t=4&save=4&wounds=2&wound_dev). Similarly, if the target has a 2+ save, [lethal](https://40k.ghostlords.com/dice/#attacks=4&bs=3&ap=-1&s=5&d=2&t=4&save=2&wounds=2&hit_leth) has less impact than [devastating](https://40k.ghostlords.com/dice/#attacks=4&bs=3&ap=-1&s=5&d=2&t=4&save=2&wounds=2&wound_dev)

Conversely, if your hit roll goes down to a 5+, then [lethal](https://40k.ghostlords.com/dice/#attacks=4&bs=5&ap=-1&s=5&d=2&t=4&save=4&wounds=2&hit_leth) is stronger than [devastating](https://40k.ghostlords.com/dice/#attacks=4&bs=5&ap=-1&s=5&d=2&t=4&save=4&wounds=2&wound_dev) because it's triggering on a higher percentage of successful hits (1/2) than successful wound rolls trigger devastating wounds.
